openapi: 3.0.0
servers:
  - description: Test
    url: http://gressling.net/v2
info:
  description: ChemInformatics EDU API
  version: "v2"
  title: ChemInformatics EDU API
  contact:
    email: thorsten.gressling@hu-berlin.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: production
    description: Deployed API
  - name: development
    description: Operations available to developers
security:
  - ApiKeyAuth: []
paths:
  /securedData:
    get:
      tags:
        - production
        - development
      summary: Retrieves secured data
      operationId: getSecuredData
      description: |
        Retrieves secured data available in the system, requires API key for access.
      parameters:
        - in: query
          name: apiKey
          description: API key for authenticating requests
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      info:
                        type: string
        '401':
          description: Unauthorized access
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: apiKey
